import { renderReviewPacketMarkdown } from '../evidence/review-packet.js';
import type { EvidenceReviewPacket } from '../evidence/types.js';
import type { PullRequestDraft, PullRequestProvider } from './types.js';

export interface BuildPullRequestDraftInput {
  provider: PullRequestProvider;
  baseBranch: string;
  headBranch: string;
  packet: EvidenceReviewPacket;
  title?: string;
  labels?: string[];
}

export function buildPullRequestDraft(input: BuildPullRequestDraftInput): PullRequestDraft {
  const riskLabel = `risk:${input.packet.riskLevel}`;
  const contractLabel = input.packet.impact.contractsTouched.length > 0 ? ['contracts-touched'] : [];
  return {
    provider: input.provider,
    title: input.title ?? `[${input.packet.taskId}] ${input.packet.goal}`,
    body: renderPrBody(input.packet),
    baseBranch: input.baseBranch,
    headBranch: input.headBranch,
    labels: [...new Set([riskLabel, 'agentforge', ...contractLabel, ...(input.labels ?? [])])],
    reviewPacket: input.packet
  };
}

function renderPrBody(packet: EvidenceReviewPacket): string {
  return [
    '## AgentForge Evidence Review',
    '',
    renderReviewPacketMarkdown(packet),
    '',
    '## Merge Guidance',
    `- Risk level: ${packet.riskLevel}`,
    `- Breaking change assessment: ${packet.breakingChangeAssessment}`,
    `- Out-of-scope files: ${packet.plannedImpactVsActual.outOfScopeFiles.join(', ') || 'None'}`,
    '',
    '<!-- Generated by AgentForge Evidence Pipeline -->'
  ].join('\n');
}
