export const IPC_CHANNELS = {
  PROJECT: {
    OPEN: 'project:open',
    SCAN: 'project:scan',
    CLOSE: 'project:close',
    GET_FACTS: 'project:getFacts',
    SEARCH_FACTS: 'project:searchFacts',
    GET_MODULES: 'project:getModules',
    GET_DEPENDENCY_GRAPH: 'project:getDependencyGraph',
    GET_FILE_TREE: 'project:getFileTree',
    UPDATE_FACT_STATUS: 'project:updateFactStatus',
    REFRESH_FACT: 'project:refreshFact',
    SWITCH: 'project:switch',
    GET_RECENT: 'project:getRecent',
    SAVE_RECENT: 'project:saveRecent',
  },
  IMPACT: {
    ANALYZE: 'impact:analyze',
    GET_MAP: 'impact:getMap',
    COMPARE_PLANNED_VS_ACTUAL: 'impact:comparePlannedVsActual',
  },
  TASK: {
    CREATE: 'task:create',
    GET_CAPSULE: 'task:getCapsule',
    UPDATE_STATUS: 'task:updateStatus',
    LIST: 'task:list',
  },
  AGENT: {
    START: 'agent:start',
    STOP: 'agent:stop',
    GET_STATUS: 'agent:getStatus',
    GET_TIMELINE: 'agent:getTimeline',
    GET_LEASES: 'agent:getLeases',
  },
  EVIDENCE: {
    GET_STACK: 'evidence:getStack',
    GET_TEST_RESULTS: 'evidence:getTestResults',
  },
  REVIEW: {
    GENERATE_PACKET: 'review:generatePacket',
    SAFE_APPLY_CHECK: 'review:safeApplyCheck',
    APPLY: 'review:apply',
  },
  GIT: {
    STATUS: 'git:status',
    DIFF: 'git:diff',
    COMMIT: 'git:commit',
    LIST_WORKTREES: 'git:listWorktrees',
    CREATE_WORKTREE: 'git:createWorktree',
    REMOVE_WORKTREE: 'git:removeWorktree',
  },
  RUNTIME: {
    EXECUTE_COMMAND: 'runtime:executeCommand',
    RUN_TESTS: 'runtime:runTests',
  },
  FILE: {
    READ: 'file:read',
    WRITE: 'file:write',
  },
  SETTINGS: {
    GET: 'settings:get',
    SET: 'settings:set',
    GET_ALL: 'settings:getAll',
    DELETE: 'settings:delete',
  },
  LSP: {
    COMPLETIONS: 'lsp:completions',
    DIAGNOSTICS: 'lsp:diagnostics',
    DEFINITION: 'lsp:definition',
    REFERENCES: 'lsp:references',
    HOVER: 'lsp:hover',
    INITIALIZE: 'lsp:initialize',
    SYMBOLS: 'lsp:symbols',
    WORKSPACE_SYMBOLS: 'lsp:workspaceSymbols',
  },
  WORKFLOW: {
    START: 'workflow:start',
    CONFIRM: 'workflow:confirm',
    COMPLETE: 'workflow:complete',
    GET_STATUS: 'workflow:getStatus',
    MERGE_WORKTREE: 'workflow:mergeWorktree',
    DISCARD_WORKTREE: 'workflow:discardWorktree',
    CLASSIFY: 'workflow:classify',
  },
  SEARCH: {
    SEARCH: 'search:search',
    REPLACE_IN_FILE: 'search:replaceInFile',
  },
  PACKAGE: {
    DETECT: 'package:detect',
    INSTALL: 'package:install',
    RUN_SCRIPT: 'package:runScript',
  },
  CI: {
    DETECT: 'ci:detect',
    GET_WORKFLOWS: 'ci:getWorkflows',
  },
  DELIVERY: {
    GENERATE_COMMIT: 'delivery:generateCommit',
    GENERATE_PR: 'delivery:generatePr',
    CREATE_PR: 'delivery:createPr',
  },
  DEBUG: {
    START: 'debug:start',
    STOP: 'debug:stop',
    SET_BREAKPOINT: 'debug:setBreakpoint',
    CONTINUE: 'debug:continue',
    STEP_OVER: 'debug:stepOver',
    STEP_INTO: 'debug:stepInto',
    STEP_OUT: 'debug:stepOut',
    GET_VARIABLES: 'debug:getVariables',
    GET_CALL_STACK: 'debug:getCallStack',
    GET_BREAKPOINTS: 'debug:getBreakpoints',
  },
  MEMORY: {
    GENERATE_PROPOSALS: 'memory:generateProposals',
    APPLY_PROPOSAL: 'memory:applyProposal',
    REJECT_PROPOSAL: 'memory:rejectProposal',
  },
  BRAIN: {
    REVERT_TASK: 'brain:revert-task',
  },
  UPDATER: {
    CHECK: 'updater:check',
    INSTALL: 'updater:install',
  },
  SANDBOX: {
    CREATE: 'sandbox:create',
    EXECUTE: 'sandbox:execute',
    STOP: 'sandbox:stop',
    STATUS: 'sandbox:status',
  },
  FEATURE: {
    CHECK: 'feature:check',
    TIER_GET: 'feature:tier:get',
    TIER_SET: 'feature:tier:set',
  },
  LEASE: {
    ESCALATION_REQUEST: 'lease:escalation:request',
    ESCALATION_RESPOND: 'lease:escalation:respond',
  },
  AUDIT: {
    QUERY: 'audit:query',
  },
} as const;

export type IpcChannel = typeof IPC_CHANNELS;
